dependencies:
- name: bdd-spring-1585413672
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: bdd-spring-1585418076
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: bdd-spring-1585419161
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
