dependencies:
- name: bdd-gh-1585256431
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: bdd-spring-1585228122
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: bdd-spring-1585254818
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: bdd-spring-1585257158
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: golang-qs
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.2
- name: node-test2
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: staging-forever-2
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
